### ISSUE TITLE
readme updates

### ISSUE THREAD

**Issue by jeffpaul** [10up/slotfill-and-filter-demos#1]
**Is your enhancement related to a problem? Please describe.**
It's not obvious the level of support provided for this repo, so let's add some clarification.

**Describe the solution you'd like**
- [x] add support level section and badge
- [ ] add license file and badge

**Designs**
n/a

**Describe alternatives you've considered**
none.

**Additional context**
none.

**Comment by jeffpaul** [comment]
@ryanwelcher if this can be installed as a WP plugin, then I'd suggest GPLv2 licensing.  Thoughts?

**Comment by ryanwelcher** [comment]
> @ryanwelcher if this can be installed as a WP plugin, then I'd suggest GPLv2 licensing. Thoughts?

100% agree - I've added that to the package.json in #6
